In [2]:
! pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

It is used to work with array .The array object in numpy is called ndarray

In [14]:
x=np.array([1,2,3,4.6,5])
y=np.array((1,2,3,4,6,5))
# x array is treated as float array as a whole while y array is treated as integer array
print(x)
print(type(x))
print(y)
print(type(y))

[1.  2.  3.  4.6 5. ]
<class 'numpy.ndarray'>
[1 2 3 4 6 5]
<class 'numpy.ndarray'>


Array function is ued to create array

In [23]:
# numpy.arange(start,stop,step)
a=np.arange(4)
print(a)
a=np.arange(1,5)
print(a)
a=np.arange(1,6,2)
print(a)
a=np.arange(-10,-4,1)
print(a)
a=np.arange(-10,-4,-1)
# if start to end traversal is not possible than it will have empty array
print(a)
a=np.arange(10,-4,-20)
# if start to end traversal is possible but after step it goes beyond end than it will have only start element
print(a)



[0 1 2 3]
[1 2 3 4]
[1 3 5]
[-10  -9  -8  -7  -6  -5]
[]
[10]


In [ ]:
# random.random is used to create array with random values between 0 to 1
a=np.random.random(size=(4,3))
print(a)
a=np.random.random(size=(4))
print(a)
a=np.random.random(size=(4,3,1))
print(a)

[[0.66038868 0.93342024 0.99846922]
 [0.37729542 0.01598568 0.03189888]
 [0.80882419 0.23521148 0.84082714]
 [0.73076043 0.4261002  0.69718996]]
[0.65881315 0.0076564  0.65656584 0.21728364]
[[[0.72599064]
  [0.42749503]
  [0.38437704]]

 [[0.5184885 ]
  [0.73882552]
  [0.89426994]]

 [[0.451789  ]
  [0.02481327]
  [0.83208093]]

 [[0.16451334]
  [0.53771669]
  [0.97918004]]]


In [52]:
# random.randint is used to create array with random integer value upto certain value ,certain size
# syntax randint(uptoValue,size=(specify dimension))
x=np.random.randint(50,size=6)
print(x)
print()
x=np.random.randint(10,size=(3,3))
print(x)
print()
x=np.random.randint(5,size=(3,4,2))
print(x)

[29 41 18 27 17 19]

[[6 8 4]
 [2 9 0]
 [7 7 3]]

[[[0 0]
  [0 1]
  [1 3]
  [1 3]]

 [[0 2]
  [1 0]
  [1 2]
  [3 3]]

 [[0 4]
  [3 2]
  [2 0]
  [1 4]]]


In [54]:
a=np.array(42)
print(a)
print("Dimension ",a.ndim)
a=np.array((42,43))
print(a)
print("Dimension ",a.ndim)
a=np.array(((42,43),(1,2)))
print(a)
print("Dimension ",a.ndim)
a=np.random.randint(50,size=(2,2,2,1))
print(a)
print("Dimension ",a.ndim)
# single value 0 dimension multiply single value 1 dimension multiple  multiple value is multi dimension 


42
Dimension  0
[42 43]
Dimension  1
[[42 43]
 [ 1  2]]
Dimension  2
[[[[12]
   [49]]

  [[32]
   [43]]]


 [[[49]
   [21]]

  [[34]
   [29]]]]
Dimension  4


In [70]:
a=np.array((1,2,3,4,5))
print(a[2])
b=np.arange(10)
print(b)
c=np.arange(12).reshape(3,4)
print(c)
print()
d=np.arange(24).reshape(2,4,3)
print(d)
# multiplication of reshape argument should be equal to argument of arrange(stop-start)


3
[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [1]:
import numpy as np
d=np.arange(24).reshape(2,4,3)
print(d[0][2][0])
d=np.arange(24).reshape(2,12)
print(d[0][6])
# Single element read 

6
6


In [6]:
# Slicing in 1D array (same as list slicing)
a=np.arange(10)
print(a[::-1])
print(a[::])
print(a[2::2])

[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [43]:
a=np.arange(12).reshape(3,4)
print(a)
print()
print(a[0,:])
print()
print(a[:,0])
print()
print(a[1:,1:])
print()
print(a[::2,:2:])
print()
print(a[::2,::3])
print()
print(a[-1::-2,-1::-3])
print()
print(a[1::,1::2])
# Slicing in 2d array a[<row slicing>,<column slicing>]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]

[0 4 8]

[[ 5  6  7]
 [ 9 10 11]]

[[0 1]
 [8 9]]

[[ 0  3]
 [ 8 11]]

[[11  8]
 [ 3  0]]

[[ 5  7]
 [ 9 11]]


In [51]:
# Slicing in 3D array
a=np.arange(24).reshape(2,4,3)
print(a)
print()
print(a[1,1::2,::2])
print()
print(a[0])
print()
print(a[0,0])
print()
print(a[1,:3])
print()
print(a[0,:2,::2])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

[[15 17]
 [21 23]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]


In [57]:
a=np.array((1,2,3,4,5))
b=np.array((5.5,6.0,7.7,2,3,7))
print(a.dtype)
# it specifies type of element contained in the array
print(b.dtype)
print(a.itemsize)
# no of bytes occupied by individual elements
print(b.itemsize)
print(a.nbytes)
# no of bytes allocated to whole array
print(b.nbytes)

int64
float64
8
8
40
48


In [8]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,1,2,3]])
print(a.ndim)
# it give dimension
print(a.shape)
# it gives rows and columns
print(a.size)
# it gives total elements in array

2
(2, 6)
12


In [21]:
a=np.zeros(10)
print(a)
a=np.zeros((3,6))
print(a)
print()
a=np.zeros((2,2,2))
print(a)
print()
a=np.ones(5,dtype='int')
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

[1 1 1 1 1]


In [27]:
print(np.identity(3,dtype='int'))
print()
print(np.identity(2))
# default data as float
np.identity(3,dtype='int')

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1. 0.]
 [0. 1.]]


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [31]:
a=np.array((1,2,3,4,5))
# Scalar operation
a=a+5
print(a)
a=np.array((1,2,3,4,5))
a=-a*5
print(a)
# Similar to -,/,**,//,% and unary operations

[ 6  7  8  9 10]
[ -5 -10 -15 -20 -25]


In [38]:
a=np.array([5,4,3,2,1])
b=np.array([1,2,3,4,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
print(a%b)

[6 6 6 6 6]
[ 4  2  0 -2 -4]
[5 8 9 8 5]
[5.  2.  1.  0.5 0.2]
[5 2 1 0 0]
[ 5 16 27 16  1]
[0 0 0 2 1]


In [5]:
a=np.array((1,2,3,4))
b=np.array((4,3,2,1))
print(a+b)
print(a*b)
print(a-b)
print(a/b)
print(a//b)
print(a**b)
print(a%b)

[5 5 5 5]
[4 6 6 4]
[-3 -1  1  3]
[0.25       0.66666667 1.5        4.        ]
[0 0 1 4]
[1 8 9 4]
[1 2 1 0]


In [7]:
a=np.array((1,2,3,4))
b=np.array((4,3,2,1))
print(np.dot(a,b))

20


In [10]:
a=np.arange(12).reshape(3,4)
print(a)
print()
b=np.arange(12).reshape(4,3)
print(b)
print()
np.dot(a,b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [25]:
x=np.arange(20).reshape(4,5)
print(x)
print(np.mean(x))
# Mean of whole array
print(np.mean(x,axis=0))
# Mean of individual column
print(np.mean(x,axis=1))
# Mean of individual row
print(np.min(x))
print(np.min(x,axis=0))
print(np.min(x,axis=1))
print(np.max(x))
print(np.max(x,axis=0))
print(np.max(x,axis=1))
print(np.average(x))
print(np.var(x))
print(np.var(x,axis=0))
print(np.var(x,axis=1))
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
9.5
[ 7.5  8.5  9.5 10.5 11.5]
[ 2.  7. 12. 17.]
0
[0 1 2 3 4]
[ 0  5 10 15]
19
[15 16 17 18 19]
[ 4  9 14 19]
9.5
33.25
[31.25 31.25 31.25 31.25 31.25]
[2. 2. 2. 2.]
190
[30 34 38 42 46]
[10 35 60 85]


In [30]:
p=np.percentile(x,25)
q=np.percentile(x,50)
r=np.percentile(x,75)
s=np.percentile(x,100)
print(p,q,r,s)

4.75 9.5 14.25 19.0


In [ ]:
a=np.arange(20).reshape(4,5)
cnt=5
for i in range(len(a)):
    a[i]+=cnt
    cnt+=5    
print(a)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


In [74]:
a=np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(3,4)
print(a)
print()
print(b)
print()
c=np.hstack((a,b))
print(c)
print()
d=np.vstack((a,b))
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [84]:
a=np.arange(24).reshape(3,8)
print(a)
print()
print(np.hsplit(a,4))
print()
# print(np.hsplit(a,3))------->Value error :array split does not result in an equal division
print(np.vsplit(a,3))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

[array([[ 0,  1],
       [ 8,  9],
       [16, 17]]), array([[ 2,  3],
       [10, 11],
       [18, 19]]), array([[ 4,  5],
       [12, 13],
       [20, 21]]), array([[ 6,  7],
       [14, 15],
       [22, 23]])]

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20, 21, 22, 23]])]


WAP to make array having corresponding max value out of two given arrays

In [95]:
a=np.array((6,3,1,5,8))
b=np.array((3,2,1,7,2))
c=np.zeros(len(a),dtype='int')
for i in range(len(a)):
    c[i]=np.max((a[i],b[i]))
print(c)

# Another solution
lst=[]
for i in range(len(a)):
    lst.append(max(a[i],b[i]))
print(np.array(lst))

[6 3 1 7 8]
[6 3 1 7 8]
