In [2]:
! pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

It is used to work with array .The array object in numpy is called ndarray

In [14]:
x=np.array([1,2,3,4.6,5])
y=np.array((1,2,3,4,6,5))
# x array is treated as float array as a whole while y array is treated as integer array
print(x)
print(type(x))
print(y)
print(type(y))

[1.  2.  3.  4.6 5. ]
<class 'numpy.ndarray'>
[1 2 3 4 6 5]
<class 'numpy.ndarray'>


Array function is ued to create array

In [23]:
# numpy.arange(start,stop,step)
a=np.arange(4)
print(a)
a=np.arange(1,5)
print(a)
a=np.arange(1,6,2)
print(a)
a=np.arange(-10,-4,1)
print(a)
a=np.arange(-10,-4,-1)
# if start to end traversal is not possible than it will have empty array
print(a)
a=np.arange(10,-4,-20)
# if start to end traversal is possible but after step it goes beyond end than it will have only start element
print(a)



[0 1 2 3]
[1 2 3 4]
[1 3 5]
[-10  -9  -8  -7  -6  -5]
[]
[10]


In [ ]:
# random.random is used to create array with random values between 0 to 1
a=np.random.random(size=(4,3))
print(a)
a=np.random.random(size=(4))
print(a)
a=np.random.random(size=(4,3,1))
print(a)

[[0.66038868 0.93342024 0.99846922]
 [0.37729542 0.01598568 0.03189888]
 [0.80882419 0.23521148 0.84082714]
 [0.73076043 0.4261002  0.69718996]]
[0.65881315 0.0076564  0.65656584 0.21728364]
[[[0.72599064]
  [0.42749503]
  [0.38437704]]

 [[0.5184885 ]
  [0.73882552]
  [0.89426994]]

 [[0.451789  ]
  [0.02481327]
  [0.83208093]]

 [[0.16451334]
  [0.53771669]
  [0.97918004]]]


In [52]:
# random.randint is used to create array with random integer value upto certain value ,certain size
# syntax randint(uptoValue,size=(specify dimension))
x=np.random.randint(50,size=6)
print(x)
print()
x=np.random.randint(10,size=(3,3))
print(x)
print()
x=np.random.randint(5,size=(3,4,2))
print(x)

[29 41 18 27 17 19]

[[6 8 4]
 [2 9 0]
 [7 7 3]]

[[[0 0]
  [0 1]
  [1 3]
  [1 3]]

 [[0 2]
  [1 0]
  [1 2]
  [3 3]]

 [[0 4]
  [3 2]
  [2 0]
  [1 4]]]


In [54]:
a=np.array(42)
print(a)
print("Dimension ",a.ndim)
a=np.array((42,43))
print(a)
print("Dimension ",a.ndim)
a=np.array(((42,43),(1,2)))
print(a)
print("Dimension ",a.ndim)
a=np.random.randint(50,size=(2,2,2,1))
print(a)
print("Dimension ",a.ndim)
# single value 0 dimension multiply single value 1 dimension multiple  multiple value is multi dimension 


42
Dimension  0
[42 43]
Dimension  1
[[42 43]
 [ 1  2]]
Dimension  2
[[[[12]
   [49]]

  [[32]
   [43]]]


 [[[49]
   [21]]

  [[34]
   [29]]]]
Dimension  4


In [70]:
a=np.array((1,2,3,4,5))
print(a[2])
b=np.arange(10)
print(b)
c=np.arange(12).reshape(3,4)
print(c)
print()
d=np.arange(24).reshape(2,4,3)
print(d)
# multiplication of reshape argument should be equal to argument of arrange(stop-start)


3
[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [2]:
import numpy as np
d=np.arange(24).reshape(2,4,3)
print(d[0][2][0])
d=np.arange(24).reshape(2,12)
print(d[0][6])

6
6
